# Generated by Django 6.0.3 on 2026-03-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='FacultyAdmin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('job_title', models.CharField(default='Faculty Administrator', max_length=100)),
                ('is_primary_admin', models.BooleanField(default=False)),
                ('can_manage_courses', models.BooleanField(default=True)),
                ('can_manage_lecturers', models.BooleanField(default=True)),
                ('can_manage_rooms', models.BooleanField(default=True)),
                ('can_manage_allocations', models.BooleanField(default=True)),
                ('can_manage_coordinators', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='api.faculty')),
            ],
            options={
                'db_table': 'FacultyAdmins',
            },
        ),
        migrations.CreateModel(
            name='ClassCoordinator',
            fields=[
                ('coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('programme', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('group_ids_managed', models.TextField(blank=True, help_text='Comma-separated group IDs')),
                ('date_appointed', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_by_admin', models.ForeignKey(db_column='appointed_by_admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'db_table': 'ClassCoordinators',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='api.faculty'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(db_column='dept_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
            ],
            options={
                'db_table': 'Lecturers',
            },
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('cross_listed_codes', models.CharField(blank=True, help_text='Comma-separated course codes', max_length=100)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('teaching_mode', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Physical', max_length=10)),
                ('lecturer', models.ForeignKey(db_column='lecturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lecturer')),
                ('primary_course', models.ForeignKey(db_column='primary_course_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('semester', models.ForeignKey(db_column='semester_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
            options={
                'db_table': 'LectureSessions',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('building_name', models.CharField(blank=True, max_length=50)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Lecture Room', 'Lecture Room'), ('Laboratory', 'Laboratory'), ('Seminar Hall', 'Seminar Hall'), ('Auditorium', 'Auditorium')], default='Lecture Room', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_faculty', models.ForeignKey(db_column='owner_faculty_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.faculty')),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=50)),
                ('feature_value', models.CharField(blank=True, max_length=100)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'db_table': 'RoomFeatures',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('group_code', models.CharField(max_length=20)),
                ('study_mode', models.CharField(choices=[('FT', 'Full Time'), ('WK', 'Weekend/Evening')], max_length=2)),
                ('approx_size', models.IntegerField()),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'db_table': 'StudentGroups',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('buffer_start_time', models.TimeField(editable=False, help_text='30 minutes before start_time (computed)')),
                ('recurrence_pattern', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('one-time', 'One Time')], default='weekly', max_length=10)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='api.lecturesession')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'db_table': 'Allocations',
                'unique_together': {('session', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='api.lecturesession')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.studentgroup')),
            ],
            options={
                'db_table': 'SessionGroups',
                'unique_together': {('session', 'group')},
            },
        ),
        migrations.CreateModel(
            name='CoordinatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('appointed_by_admin', models.ForeignKey(db_column='appointed_by_admin_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(db_column='coordinator_id', on_delete=django.db.models.deletion.CASCADE, to='api.classcoordinator')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.studentgroup')),
            ],
            options={
                'db_table': 'CoordinatorGroups',
                'unique_together': {('coordinator', 'group')},
            },
        ),
    ]
