# Generated by Django 6.0.3 on 2026-03-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='allocation_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='buffer_start_time',
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='cross_listed_codes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='lecturer',
            field=models.ForeignKey(blank=True, db_column='lecturer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lecturer'),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='session_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomfeature',
            name='feature_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['session_id'], name='Allocations_session_7539fa_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['room_id'], name='Allocations_room_id_535ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['day_of_week'], name='Allocations_day_of__6fd89c_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['session_id'], name='LectureSess_session_54a178_idx'),
        ),
    ]
